import test from 'node:test';
import assert from 'node:assert/strict';
import {EventEmitter} from 'node:events';
import {mkdtemp,mkdir,rm} from 'node:fs/promises';
import {join} from 'node:path';
import {tmpdir} from 'node:os';
import {initializeAuth} from '../src/server/auth.ts';
import {buildServer} from '../src/server/app.ts';
import {Projects} from '../src/projects.ts';
test('authenticated phase2 routes forward choices, release intent and server-owned attachments',async()=>{
 const dir=await mkdtemp(join(tmpdir(),'phase2-api-'));let app:any;const runtime:any=new EventEmitter();let sent:any,created:any;const events:string[]=[];
 Object.assign(runtime,{models:async()=>({data:[{model:'test'}]}),permissionModes:async(cwd:string)=>({current:'ask',modes:[{id:'ask',available:true}],cwd}),requestRelease:async(id:string)=>{events.push('leave:'+id);return {status:'pending'};},cancelRelease:async(id:string)=>{events.push('return:'+id);return {};},send:async(id:string,input:any)=>{sent=input;return {threadId:id};},create:async(input:any)=>{created=input;return {threadId:'created',status:'idle'};},close:async()=>{},list:async()=>({data:[],nextCursor:null}),threadCwd:async()=>null,snapshot:async()=>({thread:{id:'a',turns:[]},phase:'IDLE',pending:[]})});
 try{await mkdir(join(dir,'work'));await initializeAuth(join(dir,'data'),'phase2-api-password-long');app=await buildServer({dataDir:join(dir,'data'),origin:'http://localhost:3000',projects:new Projects(join(dir,'work')),runtime});
  assert.equal((await app.inject({url:'/api/models',headers:{host:'localhost:3000'}})).statusCode,401);
  const session=await app.inject({url:'/api/auth/session',headers:{host:'localhost:3000'}}),headers:any={host:'localhost:3000',origin:'http://localhost:3000','x-csrf-token':session.json().csrfToken,cookie:session.headers['set-cookie'].split(';')[0]};
  const login=await app.inject({method:'POST',url:'/api/auth/login',headers,payload:{password:'phase2-api-password-long'}});headers.cookie+='; '+login.headers['set-cookie'].split(';')[0];
  assert.equal((await app.inject({url:'/api/models',headers})).json().data[0].model,'test');
  assert.equal((await app.inject({url:'/api/permission-modes',headers})).json().current,'ask');
  for(const route of ['release-on-leave','cancel-release'])assert.equal((await app.inject({method:'POST',url:'/api/sessions/a/'+route,headers,payload:{}})).statusCode,200);
  assert.deepEqual(events,['leave:a','return:a']);
  const send=await app.inject({method:'POST',url:'/api/sessions/a/messages',headers,payload:{text:'hello',clientRequestId:'request-1',model:'test',effort:'medium',permissionMode:'ask',attachmentIds:[]}});assert.equal(send.statusCode,200,send.body);assert.equal(sent.effort,'medium');assert.equal(sent.permissionMode,'ask');
  const steer=await app.inject({method:'POST',url:'/api/sessions/a/messages',headers,payload:{text:'follow up',clientRequestId:'steer-request',expectedTurnId:'turn-1'}});assert.equal(steer.statusCode,200,steer.body);assert.equal(sent.expectedTurnId,'turn-1');
  assert.equal((await app.inject({method:'POST',url:'/api/sessions/a/messages',headers,payload:{text:'hi',clientRequestId:'request-2',nativeInput:[{type:'localImage',path:'C:/secret.png'}]}})).statusCode,400);
  const boundary='boundary-phase2',payload=`--${boundary}\r\nContent-Disposition: form-data; name="file"; filename="note.txt"\r\nContent-Type: text/plain\r\n\r\nattachment contents\r\n--${boundary}--\r\n`;
  const uploaded=await app.inject({method:'POST',url:'/api/uploads',headers:{...headers,'content-type':'multipart/form-data; boundary='+boundary},payload});assert.equal(uploaded.statusCode,200,uploaded.body);const uploadId=uploaded.json().uploadId;
  const newThread=await app.inject({method:'POST',url:'/api/sessions',headers,payload:{clientRequestId:'request-3',prompt:'',attachmentIds:[uploadId]}});assert.equal(newThread.statusCode,200,newThread.body);assert.equal(created.nativeInput[0].type,'text');assert.match(created.nativeInput[0].text,/note.txt/);
  assert.equal((await app.inject({url:'/api/uploads/'+uploadId,headers})).body,'attachment contents');
  assert.equal((await app.inject({url:'/api/uploads/missing',headers})).statusCode,404);
  assert.equal((await app.inject({url:'/api/sessions/a/files',headers})).statusCode,404);
  const fresh=await app.inject({method:'POST',url:'/api/uploads',headers:{...headers,'content-type':'multipart/form-data; boundary='+boundary},payload});
  const retryId=fresh.json().uploadId;
  runtime.send=async()=>{throw Object.assign(new Error('Model rejected'),{statusCode:400,code:'RUNTIME_INVALID_MODEL'});};
  assert.equal((await app.inject({method:'POST',url:'/api/sessions/a/messages',headers,payload:{text:'',clientRequestId:'rejected-request',attachmentIds:[retryId]}})).statusCode,400);
  runtime.send=async()=>({threadId:'a'});
  const retried=await app.inject({method:'POST',url:'/api/sessions/a/messages',headers,payload:{text:'',clientRequestId:'corrected-request',attachmentIds:[retryId]}});
  assert.equal(retried.statusCode,200,retried.body);
  const snapshot=await app.inject({url:'/api/sessions/a',headers});assert.equal(snapshot.json().attachmentPreviews[0].uploadId,retryId);
  const renewed=await app.inject({method:'POST',url:'/api/auth/login',headers,payload:{password:'phase2-api-password-long'}});
  headers.cookie=headers.cookie.split('; ')[0]+'; '+renewed.headers['set-cookie'].split(';')[0];
  assert.equal((await app.inject({url:'/api/uploads/'+retryId,headers})).statusCode,200);
 }finally{await app?.close();await rm(dir,{recursive:true,force:true});}
});
