// Run with Node: tests/session-toolbar.browser.mjs. No live service or real data.
import assert from 'node:assert/strict';
import {createServer} from 'vite';
import {chromium} from 'playwright';
const server=await createServer({server:{host:'127.0.0.1',port:0,strictPort:true}});await server.listen();
const browser=await chromium.launch({channel:'chrome',headless:true});
try{
 for(const width of [1280,390]){
  const page=await browser.newPage({viewport:{width,height:900}}),errors=[];
  page.on('pageerror',e=>errors.push(e.message));
  await page.goto(`http://127.0.0.1:${server.httpServer.address().port}/tests/session-toolbar.html`);
  const collapse=page.getByRole('button',{name:'收起输入区',exact:true}),expand=page.getByRole('button',{name:'展开输入',exact:true});
  await collapse.waitFor({timeout:8000});
  await page.waitForFunction(()=>document.querySelector('.session-project')?.textContent==='demo-workspace');
  const toggleMenu=()=>page.getByRole('button',{name:'操作',exact:true}).click();
  const refresh=async()=>{await toggleMenu();await page.getByRole('button',{name:'刷新当前会话'}).click();await page.waitForFunction(()=>document.querySelector('[aria-label="刷新当前会话"]')?.getAttribute('aria-busy')==='false');};
  const overflow=()=>page.locator('.session-toolbar').evaluate(e=>e.scrollWidth>e.clientWidth||[...e.children].filter(c=>c.checkVisibility()).some(c=>c.getBoundingClientRect().right>e.getBoundingClientRect().right+1));
  assert.equal(await overflow(),false,'Toolbar overflows');
  assert.equal(await page.locator('.session-header').count(),0);
  assert.equal(await page.locator('.session-project').textContent(),'demo-workspace');
  assert.equal(await page.locator('.session-title').textContent(),await page.locator('.session-title').getAttribute('title'));
  assert.equal(await page.locator('.session-title').evaluate(e=>getComputedStyle(e).maxWidth),'none');
  await page.getByRole('button',{name:'操作',exact:true}).click();
  assert.deepEqual(await page.locator('.session-actions-menu button').allTextContents(),['刷新','释放']);
  await page.keyboard.press('Escape');
  assert.equal(await page.locator('.session-actions-menu').isVisible(),false);
  assert.equal(await page.getByRole('button',{name:'操作',exact:true}).evaluate(e=>e===document.activeElement),true);
  await toggleMenu();await page.locator('.session-title').click();assert.equal(await page.locator('.session-actions-menu').isVisible(),false);
  await toggleMenu();await toggleMenu();assert.equal(await page.locator('.session-actions-menu').isVisible(),false);
  await page.evaluate(()=>testState.holdRead=true);await toggleMenu();await page.getByRole('button',{name:'刷新当前会话'}).click();
  await page.waitForFunction(()=>testState.finishRead);
  assert.match(await page.locator('.session-actions-trigger').textContent(),/刷新中/);
  assert.equal(await page.locator('.session-actions-menu').isVisible(),false);
  await page.evaluate(()=>{testState.holdRead=false;testState.finishRead();});await page.waitForFunction(()=>document.querySelector('[aria-label="刷新当前会话"]').getAttribute('aria-busy')==='false');
  await page.locator('#message').fill('保留这条演示草稿');
  await page.getByLabel('模型',{exact:true}).selectOption('demo');
  await page.locator('.attachments input[type=file]').setInputFiles({name:'example.txt',mimeType:'text/plain',buffer:Buffer.from('mock')});
  await page.waitForFunction(()=>testState.upload);
  await page.evaluate(()=>{testState.textarea=document.querySelector('#message');testState.catalogCalls=testState.calls.filter(p=>p.includes('/models')||p.includes('/permission-modes')).length;});
  const before=await page.locator('.timeline').evaluate(e=>e.clientHeight);
  await collapse.click();
  await expand.waitFor();
  assert.equal(await page.locator('#message').isVisible(),true,'Compact composer must be editable');
  assert.equal(await page.locator('.composer-compact').textContent().then(t=>t.includes('上传中')),true);
  assert.equal(await page.getByRole('button',{name:'发送',exact:true}).isDisabled(),true,'Uploading attachment must block compact send');
  await page.locator('#message').fill('紧凑栏输入');await page.locator('#message').press('End');await page.locator('#message').press(width>1000?'Shift+Enter':'Enter');await page.locator('#message').pressSequentially('第二行');
  assert.equal(await page.locator('#message').inputValue(),'紧凑栏输入\n第二行');
  assert.ok(await page.locator('.timeline').evaluate(e=>e.clientHeight)>before+80);
  assert.equal(await page.evaluate(()=>testState.upload.signal.aborted),false);
  await page.evaluate(()=>{const data=new DataTransfer();data.items.add(new File(['mock'],'hidden.png',{type:'image/png'}));document.querySelector('.composer').dispatchEvent(new ClipboardEvent('paste',{clipboardData:data,bubbles:true}));document.querySelector('.composer').dispatchEvent(new DragEvent('drop',{dataTransfer:data,bubbles:true}));});
  assert.equal(await page.evaluate(()=>testState.calls.filter(p=>p==='/api/uploads').length),1,'Hidden composer received upload');
  await page.evaluate(()=>testState.upload.finish());
  await page.waitForFunction(()=>!document.querySelector('.composer-compact').textContent.includes('上传中'));
  await expand.click();
  assert.equal(await page.locator('#message').inputValue(),'紧凑栏输入\n第二行');
  assert.equal(await page.getByLabel('模型',{exact:true}).inputValue(),'demo');
  assert.equal(await page.locator('#message').evaluate(e=>document.activeElement===e),width>1000);
  assert.equal(await page.evaluate(()=>testState.textarea===document.querySelector('#message')),true,'Composer remounted');
  assert.equal(await page.evaluate(()=>testState.catalogCalls===testState.calls.filter(p=>p.includes('/models')||p.includes('/permission-modes')).length),true,'Collapse refetched options');
  await page.getByRole('button',{name:'审批方式：恢复后确认权限'}).click();
  await collapse.focus();await page.keyboard.press('Enter');await expand.click();assert.equal(await page.locator('.permission-menu').count(),0,'Hidden permission popup survived');
  await page.screenshot({path:`.local/session-toolbar-${width}-expanded.png`});
  const timeline=page.locator('.timeline');
  await timeline.evaluate(e=>{e.scrollTop=240;e.dispatchEvent(new Event('scroll'));});
  await collapse.click();assert.ok(Math.abs(await timeline.evaluate(e=>e.scrollTop)-240)<3,'Collapse jumped history');
  await expand.click();assert.ok(Math.abs(await timeline.evaluate(e=>e.scrollTop)-240)<3,'Expand jumped history');
  await timeline.evaluate(e=>{e.scrollTop=e.scrollHeight;e.dispatchEvent(new Event('scroll'));});
  await collapse.click();await page.waitForFunction(()=>{const e=document.querySelector('.timeline');return e.scrollHeight-e.scrollTop-e.clientHeight<5;});
  await page.screenshot({path:`.local/session-toolbar-${width}-collapsed.png`});
  await page.evaluate(()=>{testState.snapshot.phase='RUNNING';testState.snapshot.activeTurnId='turn';});await refresh();
  assert.equal(await page.getByRole('button',{name:'中止',exact:true}).isVisible(),true);
  await page.getByRole('button',{name:'中止',exact:true}).click();await page.waitForFunction(()=>testState.calls.some(p=>p.endsWith('/abort')));
  await page.evaluate(()=>{testState.snapshot.phase='WAITING_INPUT';testState.snapshot.pending=[{requestId:'request',method:'item/tool/requestUserInput',params:{questions:[{id:'choice',header:'选择',question:'演示问题',options:[{label:'继续',description:'继续演示'}]}]}}];});await refresh();
  await page.getByRole('button',{name:'查看待处理'}).click();assert.equal(await expand.isVisible(),true);assert.equal(await page.locator('.approval').isVisible(),true);
  await page.evaluate(()=>{testState.snapshot.phase='EXTERNAL';testState.snapshot.activeTurnId=null;testState.snapshot.pending=[];});await refresh();
  assert.match(await page.locator('.composer-notice').textContent(),/另一个应用/);
  await page.getByRole('button',{name:'查看详情'}).click();assert.equal(await page.locator('.session-locked').isVisible(),true);await collapse.click();
  await page.evaluate(()=>testState.failRead=true);await refresh();assert.match(await page.locator('.composer-notice').textContent(),/演示同步失败|另一个应用/);
  await page.evaluate(()=>{testState.failRead=false;testState.snapshot.phase='IDLE';});await refresh();
  await expand.click();await page.locator('#message').fill('提交失败后重新编辑');await page.getByRole('button',{name:'移除附件 example.txt'}).click();
  await collapse.click();await page.getByRole('button',{name:'发送',exact:true}).click();await page.getByRole('button',{name:'重新编辑',exact:true}).waitFor();
  await page.getByRole('button',{name:'重新编辑',exact:true}).click();assert.equal(await page.locator('#message').inputValue(),'提交失败后重新编辑');
  await collapse.click();await toggleMenu();
  await page.evaluate(()=>{history.pushState(null,'','/sessions/other');window.dispatchEvent(new PopStateEvent('popstate'));});
  await page.waitForFunction(()=>document.querySelector('.session-title')?.textContent==='另一演示会话');assert.equal(await expand.isVisible(),true);assert.equal(await page.locator('.session-actions-menu').isVisible(),false);
  await page.evaluate(()=>{history.pushState(null,'','/sessions/toolbar-test');window.dispatchEvent(new PopStateEvent('popstate'));});
  await page.waitForFunction(()=>document.querySelector('.session-project')?.textContent==='demo-workspace');assert.equal(await expand.isVisible(),true);
  if(width>1000){
   await page.locator('.session-center').evaluate(e=>e.style.width='420px');assert.equal(await overflow(),false,'Narrow desktop overflow');
   assert.equal(await page.locator('.session-title').evaluate(e=>e.scrollWidth>e.clientWidth),true);
   await page.screenshot({path:'.local/session-toolbar-narrow.png'});
   await page.locator('.session-center').evaluate(e=>e.style.width='');
   assert.equal(await page.locator('.session-title').evaluate(e=>e.scrollWidth<=e.clientWidth),true,'Wide title needlessly truncated');
  }
  await toggleMenu();await page.getByRole('button',{name:'释放',exact:true}).click();await page.waitForURL('**/');
  assert.equal(await page.evaluate(()=>testState.calls.filter(p=>p.endsWith('/release')).length),1);
  assert.equal(await page.evaluate(()=>testState.calls.some(p=>p.includes('fetch'))),false,'Session action triggered Git fetch');
  await page.goto(`http://127.0.0.1:${server.httpServer.address().port}/tests/session-toolbar.html`);await collapse.waitFor();assert.equal(await expand.count(),0,'Reload retained collapsed state');
  await page.waitForFunction(()=>document.querySelector('.session-project')?.textContent==='demo-workspace');
  await page.evaluate(()=>testState.snapshot.thread.cwd='/work/demo-linux/');await refresh();assert.equal(await page.locator('.session-project').textContent(),'demo-linux');
  await page.evaluate(()=>delete testState.snapshot.thread.cwd);await refresh();assert.equal(await page.locator('.session-project').textContent(),'未关联项目');
  await page.locator('.attachments input[type=file]').setInputFiles(Array.from({length:6},(_,i)=>({name:`overflow-${i}.txt`,mimeType:'text/plain',buffer:Buffer.from('mock')})));
  await collapse.click();await page.waitForFunction(()=>document.querySelector('.composer-notice')?.textContent.includes('最多 5 个附件'));
  await page.goto(`http://127.0.0.1:${server.httpServer.address().port}/tests/session-toolbar.html?deferModels`);
  await page.waitForFunction(()=>testState.failModels&&document.querySelector('.session-project')?.textContent==='demo-workspace');
  await collapse.click();await page.evaluate(()=>testState.failModels());
  await page.waitForFunction(()=>document.querySelector('.composer-notice')?.textContent.includes('演示模型读取失败'));
  await page.getByRole('button',{name:'查看详情'}).click();assert.equal(await page.locator('.option-error').isVisible(),true);
  await page.goto(`http://127.0.0.1:${server.httpServer.address().port}/tests/session-toolbar.html`);
  await page.waitForFunction(()=>document.querySelector('.connection')?.textContent==='空闲');await collapse.click();
  await page.locator('#message').fill('紧凑发送');
  await page.locator('#message').evaluate(e=>e.dispatchEvent(new KeyboardEvent('keydown',{key:'Enter',isComposing:true,bubbles:true,cancelable:true})));
  assert.equal(await page.evaluate(()=>testState.messages?.length??0),0,'IME Enter sent a message');
  if(width<=1000){await page.locator('#message').press('End');await page.locator('#message').press('Enter');assert.equal(await page.evaluate(()=>testState.messages?.length??0),0,'Mobile Enter sent a message');await page.getByRole('button',{name:'发送',exact:true}).click();}
  else await page.locator('#message').press('Enter');
  await page.getByRole('button',{name:'重新编辑',exact:true}).waitFor();assert.equal(await page.evaluate(()=>testState.messages.length),1);
  await page.getByRole('button',{name:'重新编辑',exact:true}).click();await collapse.click();
  await page.evaluate(()=>{testState.snapshot.phase='RUNNING';testState.snapshot.activeTurnId='turn';testState.unknownSend=true;});await refresh();
  await page.getByRole('button',{name:'插话',exact:true}).click();await page.waitForFunction(()=>document.querySelector('.composer-notice')?.textContent.includes('提交结果待核实'));
  const steer=await page.evaluate(()=>testState.messages[1]);assert.equal(steer.expectedTurnId,'turn');assert.equal(steer.model,undefined);assert.equal(steer.permissionMode,undefined);
  assert.equal(await page.getByRole('button',{name:'插话',exact:true}).isDisabled(),true);
  assert.equal(await page.locator('.composer').evaluate(e=>e.scrollWidth>e.clientWidth),false,'Compact input overflows');
  await page.screenshot({path:`.local/compact-input-${width}.png`});
  assert.deepEqual(errors,[]);
  console.log(`${width}: toolbar/menu/draft/upload/scroll/status/navigation/release PASS`);
  await page.close();
 }
}finally{await browser.close();await server.close();}
