import {useEffect,useState} from 'react';
import {api} from './api.ts';
export function Notifications(){
  const supported=window.isSecureContext&&'serviceWorker' in navigator&&'PushManager' in window&&'Notification' in window;
  const [status,setStatus]=useState(supported?'尚未启用':'当前浏览器不支持通知，请使用支持 Web Push 的 HTTPS 页面。'),[enabled,setEnabled]=useState(false),[busy,setBusy]=useState(false);
  useEffect(()=>{if(!supported)return;void navigator.serviceWorker.getRegistration().then(async registration=>{const subscription=await registration?.pushManager.getSubscription();setEnabled(!!subscription);setStatus(Notification.permission==='denied'?'通知权限已被拒绝，可在浏览器设置中修改。':subscription?'此设备已有通知订阅；重新启用可同步当前登录。':'尚未启用');}).catch(()=>{});},[]);
  const enable=async()=>{setBusy(true);try{const permission=await Notification.requestPermission();if(permission!=='granted'){setStatus('未获得通知权限。');return;}const registration=await navigator.serviceWorker.getRegistration();if(!registration){setStatus('通知需要已安装服务工作线程，请在正式 HTTPS 页面刷新后重试。');return;}const {publicKey}=await api('/push/public-key');const key=Uint8Array.from(atob(publicKey.replace(/-/g,'+').replace(/_/g,'/')),c=>c.charCodeAt(0));const subscription=await registration.pushManager.getSubscription()??await registration.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:key});const json=subscription.toJSON();await api('/push/subscriptions',{endpoint:json.endpoint,keys:json.keys});setEnabled(true);setStatus('已启用：任务完成或需要确认时通知此设备。');}catch(e:any){setStatus('启用失败：'+e.message);}finally{setBusy(false);}};
  const disable=async()=>{setBusy(true);try{const registration=await navigator.serviceWorker.getRegistration(),subscription=await registration?.pushManager.getSubscription();if(subscription){await api('/push/subscriptions/remove',{endpoint:subscription.endpoint});await subscription.unsubscribe();}setEnabled(false);setStatus('通知已关闭。');}catch(e:any){setStatus('关闭失败：'+e.message);}finally{setBusy(false);}};
  return <section className="notifications"><h2>通知</h2><p className="notification-status" role="status">{status}</p><p className="muted small">通知不包含对话正文。手机打开会话时仍需连接 Tailscale；部分手机需先将本站添加到主屏幕。</p><div className="actions"><button disabled={!supported||busy} onClick={()=>void enable()}>{busy?'处理中…':enabled?'重新启用 / 同步订阅':'启用通知'}</button>{enabled?<button disabled={busy} onClick={()=>void disable()}>关闭通知</button>:null}</div></section>;
}
