import {useEffect,useRef,useState} from 'react';
import {api,type Json} from './api.ts';
import {loadTurnSettings} from './turnSettings.ts';
export type TurnSettings={model?:string;effort?:string;permissionMode?:string};
const labels:Record<string,string>={ask:'请求批准','auto-review':'帮我批准','full-access':'完全访问权限',custom:'自定义（config.toml）'};
const descriptions:Record<string,string>={ask:'需要提升文件或网络权限时由你确认','auto-review':'由 Codex 自动审查需要批准的操作','full-access':'允许沙箱外文件和网络访问，关闭常规执行审批',custom:'使用开发机配置中定义的权限'};
export function TurnOptions({value,onChange,projectId,permissions,effectiveModel,effectiveEffort,disabled=false,hidden=false,onModels,onCatalog,onError}:{value:TurnSettings;onChange:(next:TurnSettings)=>void;projectId?:string;permissions?:Json;effectiveModel?:string|null;effectiveEffort?:string|null;disabled?:boolean;hidden?:boolean;onModels?:(models:Json[])=>void;onCatalog?:(catalog:Json)=>void;onError?:(error:string)=>void}){
  const [refreshing,setRefreshing]=useState(false),[modelNotice,setModelNotice]=useState('');
  useEffect(()=>{if(!modelNotice)return;const timer=setTimeout(()=>setModelNotice(''),5000);return()=>clearTimeout(timer);},[modelNotice]);
  const [models,setModels]=useState<Json[]>([]),[catalog,setCatalog]=useState<Json>({}),[error,setError]=useState(''),[open,setOpen]=useState(false),button=useRef<HTMLButtonElement>(null),menu=useRef<HTMLDivElement>(null);
  useEffect(()=>{if(hidden)setOpen(false);},[hidden]);
  useEffect(()=>{onError?.(error?'选项读取失败：'+error:'');},[error,onError]);
  useEffect(()=>{let disposed=false;void Promise.allSettled([api('/models'),api('/permission-modes'+(projectId?'?projectId='+encodeURIComponent(projectId):''))]).then(([model,mode])=>{if(disposed)return;const errors=[];if(model.status==='fulfilled'){const items=model.value.data??model.value.models??[];setModels(items);onModels?.(items);setModelNotice(model.value.stale?'Codex 目录读取失败，显示上次成功读取的列表':'');}else errors.push(model.reason.message);if(mode.status==='fulfilled'){setCatalog(mode.value);onCatalog?.(mode.value);}else errors.push(mode.reason.message);setError(errors.join('；'));});return()=>{disposed=true;};},[projectId]);
  useEffect(()=>{if(!open)return;const close=(event:PointerEvent)=>{if(!menu.current?.contains(event.target as Node)&&!button.current?.contains(event.target as Node))setOpen(false);};document.addEventListener('pointerdown',close);menu.current?.querySelector<HTMLButtonElement>('[role=menuitemradio]:not(:disabled)')?.focus();return()=>document.removeEventListener('pointerdown',close);},[open]);
  const effective=permissions?(permissions.sandbox?.type==='dangerFullAccess'&&permissions.approvalPolicy==='never'?'full-access':permissions.sandbox?.type==='workspaceWrite'&&permissions.approvalPolicy==='on-request'?(permissions.approvalsReviewer==='auto_review'?'auto-review':permissions.approvalsReviewer==='user'?'ask':'custom'):'custom'):typeof catalog.current==='string'?catalog.current:catalog.defaultMode??'custom';
  const unverified=effectiveModel!==undefined&&!permissions&&!value.permissionMode;
  const inherited=!value.permissionMode&&!permissions&&!(catalog.modes??[]).some((m:Json)=>m.id===effective&&m.available);
  const home=effectiveModel===undefined,current=home?catalog.model??models.find(m=>m.isDefault)?.model:effectiveModel;
  const selected=value.permissionMode??(unverified?undefined:effective),model=models.find(m=>(m.model??m.id)===(value.model??current)),efforts=(model?.supportedReasoningEfforts??[]).map((effort:any)=>typeof effort==='string'?effort:effort.reasoningEffort??effort.effort);
  const last=loadTurnSettings(),displayModel=value.model??current??'',displayEffort=value.effort??(value.model&&value.model!==current?model?.defaultReasoningEffort:home?catalog.effort??model?.defaultReasoningEffort:effectiveEffort??model?.defaultReasoningEffort)??'';
  const permissionLabel=unverified?'恢复后确认权限':inherited&&!value.permissionMode?'沿用原生配置':labels[selected??'']??'权限未返回';
  const modes:Array<Json>=catalog.modes??[];
  const refreshModels=async()=>{if(refreshing)return;setRefreshing(true);setModelNotice('');try{const result=await api('/models?refresh=true');setModels(result.data);onModels?.(result.data);setModelNotice(result.stale?'Codex 目录读取失败，显示上次成功读取的列表':'已从 Codex 重新读取模型列表');}catch(e:any){setModelNotice('刷新失败，保留原列表：'+e.message);}finally{setRefreshing(false);}};
  return <div className="turn-options"><label>模型<select aria-label="模型" aria-busy={refreshing} value={displayModel} onChange={e=>{if(e.target.selectedOptions[0]?.dataset.action==='refresh'){e.target.value=displayModel;void refreshModels();}else if(!disabled){const next=e.target.value,entry=models.find(m=>(m.model??m.id)===next);onChange({...value,model:next||undefined,effort:next?entry?.defaultReasoningEffort:undefined});}}}><option value="">沿用{home?'当前配置':'当前会话'}</option>{models.map(m=>{const id=m.model??m.id;return <option key={id} value={id} disabled={disabled}>{m.displayName??id}{last.model===id?'（上一次）':''}</option>;})}{displayModel&&!models.some(m=>(m.model??m.id)===displayModel)?<option value={displayModel} disabled={disabled}>{displayModel}（待核对）</option>:null}<optgroup label="模型目录"><option value="__refresh_models__" data-action="refresh" disabled={refreshing}>{refreshing?'刷新中…':'刷新模型列表'}</option></optgroup></select></label>
    {modelNotice?<span className="model-notice" role="status">{modelNotice}</span>:null}
    <label>推理强度<select aria-label="推理强度" value={displayEffort} disabled={disabled||!efforts.length} onChange={e=>onChange({...value,effort:e.target.value||undefined})}><option value="">沿用{home?'当前配置':'当前会话'}</option>{efforts.map((id:string)=><option key={id} value={id}>{id}{last.model===displayModel&&last.effort===id?'（上一次）':''}</option>)}{displayEffort&&!efforts.includes(displayEffort)?<option value={displayEffort}>{displayEffort}（待核对）</option>:null}</select></label>
    <div className="permission-picker"><button ref={button} type="button" aria-label={'审批方式：'+permissionLabel} title={unverified?'此会话尚未由 Web 恢复，原生只读接口不返回权限。发送时确认，或选择下条消息的权限。':undefined} aria-haspopup="menu" aria-expanded={open} disabled={disabled} onClick={()=>setOpen(!open)}>{permissionLabel} ▾</button>{open?<div ref={menu} role="menu" aria-label="审批方式" className="permission-menu" onKeyDown={event=>{if(event.key==='Escape'){setOpen(false);button.current?.focus();}if(['ArrowDown','ArrowUp','Home','End'].includes(event.key)){event.preventDefault();const items=[...event.currentTarget.querySelectorAll<HTMLButtonElement>('[role=menuitemradio]:not(:disabled)')],index=items.indexOf(document.activeElement as HTMLButtonElement);items[event.key==='Home'?0:event.key==='End'?items.length-1:(index+(event.key==='ArrowDown'?1:-1)+items.length)%items.length]?.focus();}}}><div className="permission-heading">应如何批准 Codex 操作？ <a href="https://learn.chatgpt.com/docs/agent-approvals-security" target="_blank" rel="noreferrer">了解更多</a></div>{Object.entries(labels).map(([id,label])=>{const capability=modes.find(m=>m.id===id),available=capability?.available??capability?.enabled??false;return <button type="button" role="menuitemradio" aria-checked={selected===id} key={id} disabled={!available} title={capability?.reason??''} onClick={()=>{onChange({...value,permissionMode:id});setOpen(false);button.current?.focus();}}><span>{label}{selected===id?' ✓':''}</span><small>{capability?.reason??descriptions[id]}</small></button>;})}</div>:null}</div>
    {(value.model||value.effort||value.permissionMode)?<span className="muted small">{home?'新任务生效':'下条消息生效'}</span>:null}{error?<span className="option-error" role="status">选项读取失败：{error}</span>:null}</div>;
}
