import {useEffect,useRef,useState} from 'react';
import {api,type Json} from './api.ts';
export type TurnSettings={model?:string;effort?:string;permissionMode?:string};
const labels:Record<string,string>={ask:'请求批准','auto-review':'帮我批准','full-access':'完全访问权限',custom:'自定义（config.toml）'};
const descriptions:Record<string,string>={ask:'需要提升文件或网络权限时由你确认','auto-review':'由 Codex 自动审查需要批准的操作','full-access':'允许沙箱外文件和网络访问，关闭常规执行审批',custom:'使用开发机配置中定义的权限'};
export function TurnOptions({value,onChange,projectId,permissions,effectiveModel,effectiveEffort,disabled=false,hidden=false,onModels,onError}:{value:TurnSettings;onChange:(next:TurnSettings)=>void;projectId?:string;permissions?:Json;effectiveModel?:string|null;effectiveEffort?:string|null;disabled?:boolean;hidden?:boolean;onModels?:(models:Json[])=>void;onError?:(error:string)=>void}){
  const [models,setModels]=useState<Json[]>([]),[catalog,setCatalog]=useState<Json>({}),[error,setError]=useState(''),[open,setOpen]=useState(false),button=useRef<HTMLButtonElement>(null),menu=useRef<HTMLDivElement>(null);
  useEffect(()=>{if(hidden)setOpen(false);},[hidden]);
  useEffect(()=>{onError?.(error?'选项读取失败：'+error:'');},[error,onError]);
  useEffect(()=>{let disposed=false;void Promise.allSettled([api('/models'),api('/permission-modes'+(projectId?'?projectId='+encodeURIComponent(projectId):''))]).then(([model,mode])=>{if(disposed)return;const errors=[];if(model.status==='fulfilled'){const items=model.value.data??model.value.models??[];setModels(items);onModels?.(items);}else errors.push(model.reason.message);if(mode.status==='fulfilled')setCatalog(mode.value);else errors.push(mode.reason.message);setError(errors.join('；'));});return()=>{disposed=true;};},[projectId]);
  useEffect(()=>{if(!open)return;const close=(event:PointerEvent)=>{if(!menu.current?.contains(event.target as Node)&&!button.current?.contains(event.target as Node))setOpen(false);};document.addEventListener('pointerdown',close);menu.current?.querySelector<HTMLButtonElement>('[role=menuitemradio]:not(:disabled)')?.focus();return()=>document.removeEventListener('pointerdown',close);},[open]);
  const effective=permissions?(permissions.sandbox?.type==='dangerFullAccess'&&permissions.approvalPolicy==='never'?'full-access':permissions.sandbox?.type==='workspaceWrite'&&permissions.approvalPolicy==='on-request'?(permissions.approvalsReviewer==='auto_review'?'auto-review':permissions.approvalsReviewer==='user'?'ask':'custom'):'custom'):typeof catalog.current==='string'?catalog.current:catalog.defaultMode??'custom';
  const unverified=effectiveModel!==undefined&&!permissions&&!value.permissionMode;
  const inherited=!value.permissionMode&&!permissions&&!(catalog.modes??[]).some((m:Json)=>m.id===effective&&m.available);
  const selected=value.permissionMode??(unverified?undefined:effective),model=models.find(m=>(m.model??m.id)===(value.model??effectiveModel))??(effectiveModel===undefined?models.find(m=>m.isDefault):undefined),efforts=model?.supportedReasoningEfforts??[];
  const currentModel=models.find(m=>(m.model??m.id)===effectiveModel);
  const modelLabel=effectiveModel?`${currentModel?.displayName??effectiveModel}（当前）`:effectiveModel===null?'当前模型未返回':'沿用当前配置';
  const changedModel=!!value.model&&value.model!==effectiveModel;
  const effortLabel=changedModel?(model?.defaultReasoningEffort?`${model.defaultReasoningEffort}（模型默认）`:'模型默认'):effectiveEffort?`${effectiveEffort}（当前）`:effectiveModel!==undefined?'未指定或未返回':'默认';
  const permissionLabel=unverified?'恢复后确认权限':inherited&&!value.permissionMode?'沿用原生配置':labels[selected??'']??'权限未返回';
  const modes:Array<Json>=catalog.modes??[];
  return <div className="turn-options"><label>模型<select aria-label="模型" value={value.model??''} disabled={disabled} onChange={e=>onChange({...value,model:e.target.value||undefined,effort:undefined})}><option value="">{modelLabel}</option>{models.map(m=><option key={m.id??m.model} value={m.model??m.id}>{m.displayName??m.model??m.id}</option>)}{value.model&&!models.some(m=>(m.model??m.id)===value.model)?<option value={value.model}>{value.model}（待核对）</option>:null}</select></label>
    <label>推理强度<select aria-label="推理强度" value={value.effort??''} disabled={disabled||!efforts.length} onChange={e=>onChange({...value,effort:e.target.value||undefined})}><option value="">{effortLabel}</option>{efforts.map((effort:any)=>{const id=typeof effort==='string'?effort:effort.reasoningEffort??effort.effort;return <option key={id} value={id}>{id}</option>;})}</select></label>
    <div className="permission-picker"><button ref={button} type="button" aria-label={'审批方式：'+permissionLabel} title={unverified?'此会话尚未由 Web 恢复，原生只读接口不返回权限。发送时确认，或选择下条消息的权限。':undefined} aria-haspopup="menu" aria-expanded={open} disabled={disabled} onClick={()=>setOpen(!open)}>{permissionLabel} ▾</button>{open?<div ref={menu} role="menu" aria-label="审批方式" className="permission-menu" onKeyDown={event=>{if(event.key==='Escape'){setOpen(false);button.current?.focus();}if(['ArrowDown','ArrowUp','Home','End'].includes(event.key)){event.preventDefault();const items=[...event.currentTarget.querySelectorAll<HTMLButtonElement>('[role=menuitemradio]:not(:disabled)')],index=items.indexOf(document.activeElement as HTMLButtonElement);items[event.key==='Home'?0:event.key==='End'?items.length-1:(index+(event.key==='ArrowDown'?1:-1)+items.length)%items.length]?.focus();}}}><div className="permission-heading">应如何批准 Codex 操作？ <a href="https://learn.chatgpt.com/docs/agent-approvals-security" target="_blank" rel="noreferrer">了解更多</a></div>{Object.entries(labels).map(([id,label])=>{const capability=modes.find(m=>m.id===id),available=capability?.available??capability?.enabled??false;return <button type="button" role="menuitemradio" aria-checked={selected===id} key={id} disabled={!available} title={capability?.reason??''} onClick={()=>{onChange({...value,permissionMode:id});setOpen(false);button.current?.focus();}}><span>{label}{selected===id?' ✓':''}</span><small>{capability?.reason??descriptions[id]}</small></button>;})}</div>:null}</div>
    {(value.model||value.effort||value.permissionMode)?<span className="muted small">下条消息生效</span>:null}{error?<span className="option-error" role="status">选项读取失败：{error}</span>:null}</div>;
}
